SocialRichAlejandro/Models/SocialNetwork.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocialRichAlejandro.Models
{
    public class SocialNetwork
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }

        public virtual ICollection<Users> User { get; set; }
        public virtual ICollection<Networks> Networks { get; set; }
    }
}

SocialRichAlejandro/Controllers/SocialNetworkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SocialRich.Entities;
using SocialRichAlejandro.Models;
using SocialRichAlejandro.ViewModel;

namespace SocialRichAlejandro.Controllers
{
    public class SocialNetworkController : Controller
    {
        #region Properties and constructor
        private readonly Context _context;

        public SocialNetworkController(Context context)
        {
            _context = context;
        }
        #endregion

        #region Index
        [HttpGet]
        public ActionResult Index()
        {
            List<SocialNetworkViewModel> SNVMList = new List<SocialNetworkViewModel>();
            var SNList = _context.SocialNetwork.ToList();

            foreach (var socialNet in SNList)
            {
                List<Users> SNUsersList = new List<Users>();
                var NetList = _context.Networks.Where(n => n.SocialNetworksId == socialNet.Id).ToList();
                foreach (var net in NetList)
                {
                    SNUsersList.Add(_context.Users.First(u => u.Id == net.UsersId));
                }

                SocialNetworkViewModel model = new SocialNetworkViewModel
                {
                    Id = socialNet.Id,
                    Name = socialNet.Name,
                    Url = socialNet.Url,
                    SocialNetworkUsers = SNUsersList
                };

                SNVMList.Add(model);
            }
            return View(new SocialNetworkListViewModel
            {
                 SocialNetworkList = SNVMList
            });
        }
        #endregion

        #region Details
        [HttpGet]
        public ActionResult Details(int id)
        {
            return View();
        }
        #endregion

        #region Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
       

        [HttpPost]
        public ActionResult Create(AddSocialNetwork model)
        {
            try
            {
                _context.SocialNetwork.Add(new SocialNetwork
                {
                    Name = model.Name,
                    Url = model.Url
                });

                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region Edit
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region Delete
        public ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        #endregion
    }
}

SocialRichAlejandro/Views/SocialNetwork/AddSocialNetwork.cshtml
@{
    ViewData["Title"] = "AddSocialNetwork";
}

<h2>AddSocialNetwork</h2>

SocialRichAlejandro/Views/SocialNetwork/Create.cshtml
@model SocialRichAlejandro.ViewModel.AddSocialNetwork

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<div class="row">
    <div class="col-md-7">
        <h2>Añadir Red Social</h2>
        <ul>
            <form class="form-group" asp-controller="SocialNetwork" asp-action="Create" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div>
                    <label asp-for="Name">Name:</label>
                    <input asp-for="Name" type="text" name="Name" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div>
                    <label asp-for="Url">Url:</label>
                    <input asp-for="Url" type="text" name="Url" required />
                    <span asp-validation-for="Url" class="text-danger"></span>
                </div>
                <div class="button">
                    <button class="btn btn-info" type="submit">Añadir</button>
                </div>
            </form>
        </ul>
    </div>
</div>

@Html.ActionLink("Volver", "Index", "SocialNetwork", null, new { @class = "btn btn-info" })

SocialRichAlejandro/Views/SocialNetwork/Index.cshtml
@model SocialRichAlejandro.ViewModel.SocialNetworkListViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<div class="row">
    <div class="col-md-6">
        <h2>Lista de Redes Sociales y sus Usuarios</h2>
        <ul>
            @{
                foreach (var SNet in Model.SocialNetworkList)
                {
                    <li>id: @(SNet.Id) | nombre: @(SNet.Name) | Url: @(SNet.Url)</li>
                    <ul>
                        <h5>Lista de Usuarios de la Red Social</h5>
                        @{
                            foreach (var usuario in SNet.SocialNetworkUsers)
                            {
                                <li>Id del Usuario: @(usuario.Id)</li>
                                <li>Nombre del Usuario: @(usuario.Name)</li>
                            }
                        }
                    </ul>
                }
            }
        </ul>
    </div>
    <div class="col-lg-6">
        @Html.ActionLink("Añadir Red Social", "Create", "SocialNetwork", null, new { @class = "btn btn-info" })
    </div>

</div>

@Html.ActionLink("Volver", "Index", "Home", null, new { @class = "btn btn-info" })